version: 2
jobs:
  build:
    working_directory: ~/spotify-web-api-kotlin
    docker:
      - image: gradle
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew test -PclientId=$SPOTIFY_CLIENT_ID -PclientSecret=$SPOTIFY_CLIENT_SECRET
