# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI Test Workflow

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  repository_dispatch:
    types: [ok-to-test-command]

jobs:
  test_android_jvm_linux_trusted:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    environment: testing
    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Install java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Install curl
      run: sudo apt-get install -y curl libcurl4-openssl-dev
    - name: Test secret
      run: echo "client id secret is $SPOTIFY_CLIENT_ID"
    - name: Test android
      run: ./gradlew testDebugUnitTest
    - name: Test jvm
      run: ./gradlew jvmTest
    - name: Archive test results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: build/reports
  test_android_jvm_linux_untrusted:
    runs-on: ubuntu-latest
    if:
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.slash_command.sha != '' &&
      contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.sha) &&
      github.event.pull_request.head.repo.full_name != github.repository
    environment: testing
    env:
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
    steps:
      - name: Fork based /ok-to-test checkout
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
      - name: Install java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install curl
        run: sudo apt-get install -y curl libcurl4-openssl-dev
      - name: Test secret
        run: echo "client id secret is $SPOTIFY_CLIENT_ID"
      - name: Test android
        run: ./gradlew testDebugUnitTest
      - name: Test jvm
        run: ./gradlew jvmTest
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: build/reports